
import { PokemonEntry, Milestone, Rarity } from './types';

export const SPECIAL_ROUTES = [
  "Beyond the Sea",
  "Night Sky's Edge",
  "Yellow Forest",
  "Rally",
  "Sightseeing",
  "Winner's Path",
  "Amity Meadow"
];

export const POST_NATIONAL_ROUTES = [
  "Quiet Cave",
  "Icy Mountain Rd.",
  "Stormy Beach",
  "Treehouse",
  "Resort",
  "Big Forest",
  "Hoenn Field",
  "Scary Cave",
  "Sinnoh Field",
  "Warm Beach",
  "White Lake",
  "Volcano Path"
];

export const MILESTONES: Milestone[] = [
  { 
    id: 1, 
    name: "New Bark Beginnings", 
    pointsStandard: 20, 
    pointsCompletionist: 20,
    description: "Choose your starter (Chikorita, Cyndaquil, or Totodile) and receive the Mystery Egg from Mr. Pokémon.",
    stopAt: "Starting Town Exit"
  },
  { 
    id: 2, 
    name: "The First Challenge", 
    pointsStandard: 60, 
    pointsCompletionist: 60,
    description: "Defeat Falkner at the Violet City Gym to earn the Zephyr Badge.",
    stopAt: "Falkner Gym Exit"
  },
  { 
    id: 3, 
    name: "Azalea & Team Rocket", 
    pointsStandard: 120, 
    pointsCompletionist: 120,
    description: "Clear Slowpoke Well of Team Rocket and defeat Bugsy for the Hive Badge.",
    stopAt: "Bugsy Gym Exit"
  },
  { 
    id: 4, 
    name: "Goldenrod City", 
    pointsStandard: 200, 
    pointsCompletionist: 200,
    description: "Earn the Plain Badge from Whitney and collect the SquirtBottle.",
    stopAt: "Whitney Gym Exit"
  },
  { 
    id: 5, 
    name: "The Burned Tower", 
    pointsStandard: 290, 
    pointsCompletionist: 290,
    description: "Encounter Eusine and the Legendary Beasts (Raikou, Entei, and Suicune), then defeat Morty in Ecruteak City for the Fog Badge.",
    stopAt: "Morty Gym Exit"
  },
  { 
    id: 6, 
    name: "The Lighthouse Quest", 
    pointsStandard: 390, 
    pointsCompletionist: 390,
    description: "Surf to Olivine City, then to Cianwood City to get the SecretPotion for Amphy the Mareep.",
    stopAt: "Olivine Lighthouse Potion Delivery"
  },
  { 
    id: 7, 
    name: "Cianwood Showdown", 
    pointsStandard: 500, 
    pointsCompletionist: 500,
    description: "Defeat Chuck for the Storm Badge and receive Fly from his wife.",
    stopAt: "Chuck Gym Exit"
  },
  { 
    id: 8, 
    name: "The Mineral Badge", 
    pointsStandard: 620, 
    pointsCompletionist: 620,
    description: "Return the medicine to the Lighthouse and defeat Jasmine in Olivine City.",
    stopAt: "Jasmine Gym Exit"
  },
  { 
    id: 9, 
    name: "Lake of Rage", 
    pointsStandard: 750, 
    pointsCompletionist: 750,
    description: "Battle or catch the Shiny Red Gyarados and team up with Lance to raid the Team Rocket HQ in Mahogany Town.",
    stopAt: "Team rocket hideout Gym exit"
  },
  { 
    id: 10, 
    name: "The Cold Front", 
    pointsStandard: 890, 
    pointsCompletionist: 990,
    description: "Defeat Pryce at the Mahogany Gym for the Glacier Badge.",
    stopAt: "Pryce Gym Exit"
  },
  { 
    id: 11, 
    name: "Radio Tower Siege", 
    pointsStandard: 950, 
    pointsCompletionist: 1150,
    description: "Return to Goldenrod City to defeat Executive Archer and disband Team Rocket for good.",
    stopAt: "Radio Tower Exit"
  },
  { 
    id: 12, 
    name: "The Dragon’s Den", 
    pointsStandard: 1050, 
    pointsCompletionist: 1350,
    description: "Brave the Ice Path to reach Blackthorn City. Defeat Clair, then pass the Master’s test in the Dragon's Den to receive the Rising Badge.",
    stopAt: "Clair Gym Exit"
  },
  { 
    id: 13, 
    name: "The Kimono Girls", 
    pointsStandard: 1150, 
    pointsCompletionist: 1550,
    description: "Defeat all five Kimono Girls in Ecruteak City to prove your worth.",
    stopAt: "Dance Theater Exit"
  },
  { 
    id: 14, 
    name: "The Tidal Guardian", 
    pointsStandard: 1200, 
    pointsCompletionist: 1700,
    description: "Head to the Whirl Islands to encounter and catch Lugia (Level 45).",
    stopAt: "Whirl Islands Exit"
  },
  { 
    id: 15, 
    name: "The Johto League", 
    pointsStandard: 1245, 
    pointsCompletionist: 1820,
    description: "Traverse Victory Road and defeat the Elite Four and Champion Lance to become the Johto Champion.",
    stopAt: "Home Exit"
  },
  { 
    id: 16, 
    name: "Set Sail for Kanto", 
    pointsStandard: 1350, 
    pointsCompletionist: 2000,
    description: "Receive the S.S. Ticket from Elm and board the S.S. Aqua in Olivine City to reach Vermilion City.",
    stopAt: "Olivine"
  },
  { 
    id: 17, 
    name: "The Lightning American", 
    pointsStandard: 1500, 
    pointsCompletionist: 2225,
    description: "Cut down the tree blocking the gym and defeat Lt. Surge to earn the Thunder Badge.",
    stopAt: "Lt Surge Exit"
  },
  { 
    id: 18, 
    name: "The Master of Psychic", 
    pointsStandard: 1650, 
    pointsCompletionist: 2450,
    description: "Travel to Saffron City and defeat Sabrina in the teleporting gym to earn the Marsh Badge.",
    stopAt: "Sabrina Exit"
  },
  { 
    id: 19, 
    name: "The Power Plant Crisis", 
    pointsStandard: 1800, 
    pointsCompletionist: 2675,
    description: "Chase the Rocket Grunt to Cerulean City to retrieve the Machine Part and restore power to the Kanto Power Plant.",
    stopAt: "Power Plant Exit"
  },
  { 
    id: 20, 
    name: "The Misty Encounter", 
    pointsStandard: 1950, 
    pointsCompletionist: 2900,
    description: "Interrupt Misty’s date at Cerulean Cape, then defeat her at the gym to earn the Cascade Badge.",
    stopAt: "Misty Exit"
  },
  { 
    id: 21, 
    name: "The Nature Lover", 
    pointsStandard: 2100, 
    pointsCompletionist: 3125,
    description: "Travel to Celadon City and defeat Erika to earn the Rainbow Badge.",
    stopAt: "Erika Exit"
  },
  { 
    id: 22, 
    name: "The Ninja’s Daughter", 
    pointsStandard: 2250, 
    pointsCompletionist: 3350,
    description: "Head south to Fuchsia City and defeat Janine (Koga’s daughter) to earn the Soul Badge.",
    stopAt: "Janine Exit"
  },
  { 
    id: 23, 
    name: "Electricity Restored", 
    pointsStandard: 2400, 
    pointsCompletionist: 3575,
    description: "Upgrade your Radio Card in Lavender Town and use the Poké Flute channel to wake the Snorlax blocking the path.",
    stopAt: "Fishing Guru 3 Exit"
  },
  { 
    id: 24, 
    name: "Pewter City Showdown", 
    pointsStandard: 2550, 
    pointsCompletionist: 3800,
    description: "Navigate through Diglett’s Cave to Pewter City and defeat Brock to earn the Boulder Badge.",
    stopAt: "Brock Exit"
  },
  { 
    id: 25, 
    name: "Rock Tunnel & Lavender", 
    pointsStandard: 2700, 
    pointsCompletionist: 4025,
    description: "Head East from Pewter City toward Mt. Moon and face off against your Rival one last time.",
    stopAt: "Battle with Rival at route 3"
  },
  { 
    id: 26, 
    name: "Cinnabar & Seafoam", 
    pointsStandard: 2850, 
    pointsCompletionist: 4250,
    description: "Surf to the Seafoam Islands to find Blaine (whose gym was destroyed) and defeat him for the Volcano Badge.",
    stopAt: "Blaine Exit"
  },
  { 
    id: 27, 
    name: "The Final Badge", 
    pointsStandard: 3000, 
    pointsCompletionist: 4475,
    description: "Return to Viridian City and defeat the Gym Leader, Blue, to earn the Earth Badge.",
    stopAt: "Blue Exit"
  },
  { 
    id: 28, 
    name: "Oak's Approval", 
    pointsStandard: 3100, 
    pointsCompletionist: 4625,
    description: "Return to Pallet Town and show Professor Oak all 16 Badges to gain permission to enter Mt. Silver.",
    stopAt: "Pallet Town Lab Exit"
  },
  { 
    id: 29, 
    name: "The Silver Path", 
    pointsStandard: 3200, 
    pointsCompletionist: 4775,
    description: "Travel west through the Reception Gate and Route 28 to reach the entrance of the Silver Cave.",
    stopAt: "Mt. Silver Cave Entrance"
  },
  { 
    id: 30, 
    name: "The Peak of Mt. Silver", 
    pointsStandard: 3330, 
    pointsCompletionist: 4945,
    description: "Scale the snowy summit to challenge Red, the ultimate Pokémon Trainer.",
    stopAt: "Ending"
  },
];

export const ROUTE_ORDER = [
  "Refreshing Field",
  "Noisy Forest",
  "Rugged Road",
  "Beautiful Beach",
  "Suburban Area",
  "Dim Cave",
  "Blue Lake",
  "Town Outskirts",
  "Hoenn Field",
  "Warm Beach",
  "Volcano Path",
  "Treehouse",
  "Scary Cave",
  "Sinnoh Field",
  "Icy Mountain Rd.",
  "Big Forest",
  "White Lake",
  "Stormy Beach",
  "Resort",
  "Quiet Cave",
  "Beyond the Sea",
  "Night Sky's Edge",
  "Yellow Forest",
  "Rally",
  "Sightseeing",
  "Winner's Path",
  "Amity Meadow"
];

// Helper to create entries quickly. Includes gender/item in ID hash to ensure uniqueness.
const p = (dexId: number, name: string, gender: string, route: string, method: string, steps: string, rarity: Rarity, item: string, points: number): PokemonEntry => ({
  id: `${name}-${route}-${method}-${steps}-${rarity}-${item}-${gender}`.replace(/\s+/g, '-').toLowerCase(),
  dexId, name, gender, route, unlockMethod: method, steps, rarity, item: item === "None" ? "" : item, points
});

export const POKEMON_DB: PokemonEntry[] = [
  // Post-National
  p(442, "Spiritomb", "♂", "Quiet Cave", "100,000 watts", "10,000+", Rarity.VeryRare, "None", 85),
  p(446, "Munchlax", "♂", "Quiet Cave", "100,000 watts", "10,000+", Rarity.VeryRare, "None", 85),
  p(361, "Snorunt", "♀", "Icy Mountain Rd.", "30,000 watts", "10,000+", Rarity.Common, "None", 55),
  p(459, "Snover", "♂", "Icy Mountain Rd.", "30,000 watts", "10,000+", Rarity.Common, "None", 55),
  p(456, "Finneon", "♀", "Stormy Beach", "65,000 watts", "4,000+", Rarity.Rare, "None", 55),
  p(351, "Castform", "♀", "Treehouse", "15,000 watts", "5,000+", Rarity.Rare, "None", 55),
  p(352, "Kecleon", "♂", "Treehouse", "15,000 watts", "5,000+", Rarity.Rare, "None", 55),
  p(349, "Feebas", "♂", "Quiet Cave", "100,000 watts", "500+", Rarity.Rare, "None", 45),
  p(25, "Pikachu", "♀", "Resort", "80,000 watts", "8,000+", Rarity.Common, "None", 45),
  p(417, "Pachirisu", "♀", "Resort", "80,000 watts", "8,000+", Rarity.Common, "None", 45),
  p(357, "Tropius", "♀", "Big Forest", "40,000 watts", "6,000+", Rarity.Common, "None", 40),
  p(438, "Bonsly", "♂", "Big Forest", "40,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(300, "Skitty", "♀", "Hoenn Field", "5,000 watts", "7,500+", Rarity.Common, "None", 40),
  p(105, "Marowak", "♀", "Scary Cave", "20,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(128, "Tauros", "♂", "Scary Cave", "20,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(415, "Combee", "♂", "Sinnoh Field", "25,000 watts", "7,000+", Rarity.Common, "None", 40),
  p(439, "Mime Jr.", "♂", "Sinnoh Field", "25,000 watts", "7,000+", Rarity.Common, "None", 40),
  p(320, "Wailmer", "♀", "Warm Beach", "7,500 watts", "7,000+", Rarity.Common, "None", 40),
  p(298, "Azurill", "♀", "Warm Beach", "7,500 watts", "5,000+", Rarity.Common, "None", 40),
  p(200, "Misdreavus", "♀", "White Lake", "50,000 watts", "6,000+", Rarity.Common, "None", 40),
  p(433, "Chingling", "♀", "White Lake", "50,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(264, "Linoone", "♀", "Hoenn Field", "5,000 watts", "5,000+", Rarity.VeryCommon, "None", 30),
  p(433, "Chingling", "♀", "Quiet Cave", "100,000 watts", "500+", Rarity.Common, "None", 30),
  p(35, "Clefairy", "♀", "Resort", "80,000 watts", "4,000+", Rarity.VeryCommon, "None", 30),
  p(39, "Jigglypuff", "♀", "Resort", "80,000 watts", "4,000+", Rarity.VeryCommon, "None", 30),
  p(403, "Shinx", "♀", "Sinnoh Field", "25,000 watts", "3,000+", Rarity.VeryCommon, "None", 30),
  p(406, "Budew", "♂", "Sinnoh Field", "25,000 watts", "3,000+", Rarity.VeryCommon, "None", 30),
  p(422, "Shellos", "♀", "Stormy Beach", "65,000 watts", "5,000+", Rarity.VeryCommon, "None", 30),
  p(218, "Slugma", "♀", "Volcano Path", "10,000 watts", "5,000+", Rarity.VeryCommon, "None", 30),
  p(307, "Meditite", "♂", "Volcano Path", "10,000 watts", "5,000+", Rarity.VeryCommon, "None", 30),
  p(114, "Tangela", "♀", "Big Forest", "40,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(400, "Bibarel", "♀", "Big Forest", "40,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(313, "Volbeat", "♂", "Hoenn Field", "5,000 watts", "2,000+", Rarity.VeryCommon, "None", 25),
  p(314, "Illumise", "♀", "Hoenn Field", "5,000 watts", "2,000+", Rarity.VeryCommon, "None", 25),
  p(436, "Bronzor", "-", "Icy Mountain Rd.", "30,000 watts", "3,000+", Rarity.VeryCommon, "None", 25),
  p(215, "Sneasel", "♂", "Icy Mountain Rd.", "30,000 watts", "3,000+", Rarity.VeryCommon, "None", 25),
  p(177, "Natu", "♀", "Scary Cave", "20,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(86, "Seel", "♀", "Stormy Beach", "65,000 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(203, "Girafarig", "♀", "Treehouse", "15,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(234, "Stantler", "♀", "Treehouse", "15,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(111, "Rhyhorn", "♂", "Volcano Path", "10,000 watts", "2,000+", Rarity.VeryCommon, "None", 25),
  p(228, "Houndour", "♂", "Volcano Path", "10,000 watts", "2,000+", Rarity.VeryCommon, "None", 25),
  p(116, "Horsea", "♀", "Warm Beach", "7,500 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(318, "Carvanha", "♀", "Warm Beach", "7,500 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(418, "Buizel", "♂", "White Lake", "50,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(42, "Golbat", "♂", "Scary Cave", "20,000 watts", "500+", Rarity.VeryCommon, "None", 20),
  p(129, "Magikarp", "♀", "Stormy Beach", "65,000 watts", "500+", Rarity.VeryCommon, "None", 20),
  p(93, "Haunter", "♂", "White Lake", "50,000 watts", "500+", Rarity.VeryCommon, "None", 20),
  p(102, "Exeggcute", "♀", "Big Forest", "40,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(179, "Mareep", "♂", "Big Forest", "40,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(263, "Zigzagoon", "♀", "Hoenn Field", "5,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(265, "Wurmple", "♀", "Hoenn Field", "5,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(179, "Mareep", "♀", "Icy Mountain Rd.", "30,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(220, "Swinub", "♀", "Icy Mountain Rd.", "30,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(42, "Golbat", "♂", "Quiet Cave", "100,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(164, "Noctowl", "♀", "Quiet Cave", "100,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(183, "Marill", "♀", "Resort", "80,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(187, "Hoppip", "♀", "Resort", "80,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(66, "Machop", "♂", "Scary Cave", "20,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(92, "Gastly", "♀", "Scary Cave", "20,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(399, "Bidoof", "♀", "Sinnoh Field", "25,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(401, "Kricketot", "♂", "Sinnoh Field", "25,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(54, "Psyduck", "♀", "Stormy Beach", "65,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(90, "Shellder", "♂", "Stormy Beach", "65,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(44, "Gloom", "♀", "Treehouse", "15,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(70, "Weepinbell", "♂", "Treehouse", "15,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(74, "Geodude", "♂", "Volcano Path", "10,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(77, "Ponyta", "♀", "Volcano Path", "10,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(118, "Goldeen", "♀", "Warm Beach", "7,500 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(129, "Magikarp", "♀", "Warm Beach", "7,500 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(170, "Chinchou", "♀", "White Lake", "50,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(223, "Remoraid", "♀", "White Lake", "50,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  
  // Pre-National
  p(239, "Elekid", "♂", "Suburban Area", "500 watts", "5,000+", Rarity.VeryRare, "None", 70),
  p(147, "Dratini", "♀", "Blue Lake", "2,000 watts", "5,000+", Rarity.Rare, "None", 55),
  p(92, "Gastly", "♀", "Dim Cave", "1,000 watts", "5,000+", Rarity.Rare, "None", 55),
  p(202, "Wobbuffet", "♀", "Noisy Forest", "Default", "4,000+", Rarity.Rare, "None", 55),
  p(238, "Smoochum", "♀", "Dim Cave", "1,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(240, "Magby", "♂", "Rugged Road", "50 watts", "5,000+", Rarity.Common, "None", 40),
  p(81, "Magnemite", "-", "Suburban Area", "500 watts", "4,000+", Rarity.Common, "None", 40),
  p(63, "Abra", "♀", "Town Outskirts", "3,000 watts", "5,000+", Rarity.Common, "None", 40),
  p(115, "Kangaskhan", "♀", "Refreshing Field", "Default", "3,000+", Rarity.Common, "None", 35),
  p(198, "Murkrow", "♀", "Suburban Area", "500 watts", "1,000+", Rarity.Common, "None", 35),
  p(54, "Psyduck", "♀", "Beautiful Beach", "200 watts", "4,000+", Rarity.VeryCommon, "None", 30),
  p(120, "Staryu", "-", "Beautiful Beach", "200 watts", "5,000+", Rarity.VeryCommon, "None", 30),
  p(60, "Poliwag", "♀", "Blue Lake", "2,000 watts", "4,000+", Rarity.VeryCommon, "None", 30),
  p(95, "Onix", "♂", "Rugged Road", "50 watts", "4,000+", Rarity.VeryCommon, "None", 30),
  p(60, "Poliwag", "♂", "Beautiful Beach", "200 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(79, "Slowpoke", "♂", "Beautiful Beach", "200 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(92, "Gastly", "♀", "Dim Cave", "1,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(95, "Onix", "♂", "Dim Cave", "1,000 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(69, "Bellsprout", "♀", "Noisy Forest", "Default", "3,000+", Rarity.VeryCommon, "None", 25),
  p(84, "Doduo", "♀", "Refreshing Field", "Default", "2,000+", Rarity.VeryCommon, "None", 25),
  p(66, "Machop", "♀", "Rugged Road", "50 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(77, "Ponyta", "♀", "Rugged Road", "50 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(81, "Magnemite", "-", "Suburban Area", "500 watts", "1,000+", Rarity.VeryCommon, "None", 25),
  p(100, "Voltorb", "-", "Town Outskirts", "3,000 watts", "3,000+", Rarity.VeryCommon, "None", 25),
  p(88, "Grimer", "♂", "Town Outskirts", "3,000 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(109, "Koffing", "♀", "Town Outskirts", "3,000 watts", "1,500+", Rarity.VeryCommon, "None", 25),
  p(90, "Shellder", "♀", "Blue Lake", "2,000 watts", "500+", Rarity.VeryCommon, "None", 20),
  p(98, "Krabby", "♂", "Blue Lake", "2,000 watts", "500+", Rarity.VeryCommon, "None", 20),
  p(46, "Paras", "♀", "Noisy Forest", "Default", "700+", Rarity.VeryCommon, "None", 20),
  p(48, "Venonat", "♂", "Noisy Forest", "Default", "700+", Rarity.VeryCommon, "None", 20),
  p(29, "Nidoran♀", "♀", "Refreshing Field", "Default", "500+", Rarity.VeryCommon, "None", 20),
  p(32, "Nidoran♂", "♂", "Refreshing Field", "Default", "500+", Rarity.VeryCommon, "None", 20),
  p(138, "Sunkern", "♀", "Beautiful Beach", "200 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(194, "Wooper", "♂", "Beautiful Beach", "200 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(72, "Tentacool", "♀", "Blue Lake", "2,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(118, "Goldeen", "♀", "Blue Lake", "2,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(41, "Zubat", "♂", "Dim Cave", "1,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(66, "Machop", "♂", "Dim Cave", "1,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(21, "Spearow", "♂", "Noisy Forest", "Default", "0+", Rarity.VeryCommon, "None", 15),
  p(43, "Oddish", "♀", "Noisy Forest", "Default", "0+", Rarity.VeryCommon, "None", 15),
  p(16, "Pidgey", "♂", "Refreshing Field", "Default", "0+", Rarity.VeryCommon, "None", 15),
  p(161, "Sentret", "♀", "Refreshing Field", "Default", "0+", Rarity.VeryCommon, "None", 15),
  p(74, "Geodude", "♀", "Rugged Road", "50 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(163, "Hoothoot", "♀", "Rugged Road", "50 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(19, "Rattata", "♀", "Suburban Area", "500 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(163, "Hoothoot", "♀", "Suburban Area", "500 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(19, "Rattata", "♀", "Town Outskirts", "3,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  p(162, "Furret", "♂", "Town Outskirts", "3,000 watts", "0+", Rarity.VeryCommon, "None", 15),
  
  // Special Event
  p(255, "Torchic", "♂", "Sightseeing", "Event", "10,000+", Rarity.VeryRare, "None", 85),
  p(25, "Pikachu (Fly)", "♂", "Yellow Forest", "Event", "10,000+", Rarity.VeryRare, "Shuca Berry", 85),
  p(446, "Munchlax", "♂", "Winner's Path", "Event", "8,000+", Rarity.VeryRare, "Leftovers", 75),
  p(25, "Pikachu (Surf)", "♀", "Yellow Forest", "Event", "9,500+", Rarity.VeryRare, "Lum Berry", 75),
  p(224, "Octillery", "♀", "Beyond the Sea", "GTS Trade", "5,000+", Rarity.VeryRare, "Focus Band", 70),
  p(133, "Eevee", "♂", "Sightseeing", "Event", "7,000+", Rarity.VeryRare, "None", 70),
  p(25, "Pikachu (Bal)", "♀", "Yellow Forest", "Event", "5,000+", Rarity.VeryRare, "Sitrus Berry", 70),
  p(374, "Beldum", "-", "Winner's Path", "Event", "8,000+", Rarity.Rare, "Shuca Berry", 60),
  p(239, "Elekid", "♂", "Amity Meadow", "Event", "5,000+", Rarity.Rare, "Tamato Berry", 55),
  p(240, "Magby", "♂", "Amity Meadow", "Event", "5,000+", Rarity.Rare, "Kelpsy Berry", 55),
  p(120, "Staryu", "-", "Beyond the Sea", "GTS Trade", "5,000+", Rarity.Rare, "Water Stone", 55),
  p(302, "Sableye", "♀", "Rally", "Event", "1,000+", Rarity.Rare, "None", 50),
  p(441, "Chatot", "♂", "Rally", "Event", "1,000+", Rarity.Rare, "None", 50),
  p(279, "Pelipper", "♂", "Sightseeing", "Event", "3,000+", Rarity.Rare, "None", 50),
  p(61, "Poliwhirl", "♀", "Sightseeing", "Event", "2,000+", Rarity.Rare, "None", 50),
  p(25, "Pikachu", "♂", "Yellow Forest", "Event", "2,000+", Rarity.Rare, "Leppa Berry", 50),
  p(35, "Clefairy", "♂", "Night Sky's Edge", "Jirachi", "5,000+", Rarity.Common, "None", 40),
  p(39, "Jigglypuff", "♂", "Night Sky's Edge", "Jirachi", "5,000+", Rarity.Common, "None", 40),
  p(440, "Happiny", "♀", "Amity Meadow", "Event", "2,000+", Rarity.Common, "Pomeg Berry", 35),
  p(238, "Smoochum", "♀", "Amity Meadow", "Event", "2,000+", Rarity.Common, "Hondew Berry", 35),
  p(222, "Corsola", "♀", "Beyond the Sea", "GTS Trade", "2,500+", Rarity.Common, "None", 35),
  p(116, "Horsea", "♂", "Beyond the Sea", "GTS Trade", "2,500+", Rarity.Common, "None", 35),
  p(116, "Horsea", "♂", "Winner's Path", "Event", "3,000+", Rarity.Common, "Dragon Scale", 35),
  p(355, "Duskull", "♂", "Winner's Path", "Event", "3,000+", Rarity.Common, "Reaper Cloth", 35),
  p(25, "Pikachu", "♀", "Rally", "Event", "500+", Rarity.Common, "None", 30),
  p(453, "Croagunk", "♂", "Rally", "Event", "500+", Rarity.Common, "None", 30),
  p(41, "Zubat", "♂", "Night Sky's Edge", "Jirachi", "2,500+", Rarity.VeryCommon, "None", 25),
  p(163, "Hoothoot", "♀", "Night Sky's Edge", "Jirachi", "2,500+", Rarity.VeryCommon, "None", 25),
  p(173, "Cleffa", "♀", "Amity Meadow", "Event", "0+", Rarity.VeryCommon, "Qualot Berry", 15),
  p(174, "Igglybuff", "♂", "Amity Meadow", "Event", "0+", Rarity.VeryCommon, "Grepa Berry", 15),
  p(170, "Chinchou", "♀", "Beyond the Sea", "GTS Trade", "0+", Rarity.VeryCommon, "None", 15),
  p(223, "Remoraid", "♂", "Beyond the Sea", "GTS Trade", "0+", Rarity.VeryCommon, "None", 15),
  p(74, "Geodude", "♂", "Night Sky's Edge", "Jirachi", "0+", Rarity.VeryCommon, "None", 15),
  p(95, "Onix", "♀", "Night Sky's Edge", "Jirachi", "0+", Rarity.VeryCommon, "None", 15),
  p(417, "Pachirisu", "♂", "Rally", "Event", "0+", Rarity.VeryCommon, "None", 15),
  p(427, "Buneary", "♀", "Rally", "Event", "0+", Rarity.VeryCommon, "None", 15),
  p(52, "Meowth", "♂", "Sightseeing", "Event", "0+", Rarity.VeryCommon, "None", 15),
  p(25, "Pikachu", "♀", "Sightseeing", "Event", "0+", Rarity.VeryCommon, "None", 15),
  p(129, "Magikarp", "♂", "Winner's Path", "Event", "0+", Rarity.VeryCommon, "Wacan Berry", 15),
  p(436, "Bronzor", "-", "Winner's Path", "Event", "0+", Rarity.VeryCommon, "Occa Berry", 15),
  p(25, "Pikachu", "♂", "Yellow Forest", "Event", "0+", Rarity.VeryCommon, "TinyMushroom", 15),
  p(25, "Pikachu", "♀", "Yellow Forest", "Event", "0+", Rarity.VeryCommon, "Oran Berry", 15),
];
